services:
  - type: web
    name: be-todo
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "file:/app/data/database.sqlite"
      - key: PORT
        value: 5000
    disk:
      name: sqlite-data
      mountPath: /app/data
      sizeGB: 1
    healthCheckPath: /api/health

  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://be-todo.onrender.com # Update with your actual backend URL
    buildCommand: npm install && npm run build
    startCommand: npm start